### ISSUE TITLE
Can we get a percentage of negative , positive and neutral ? 

### ISSUE THREAD

**Issue by ghost** [Sentimentron/dracula-sentiment-node#1]
Hello , 
Can we get a percentage of **negative** , **positive** and **neutral** ? 
thank you.

**Comment by Sentimentron** [comment]
Sorry it took a while to get around to implementing it, version 1.1.1 of the package includes a `score` function which you can use to get the negative, neutral and positive scores in an array in that order. 

Let me know how you get on! :D
